name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          unityVersion: 2021.3.16f1
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: DragonBoyBrasil.apk
          path: build/Android/Android.apk
