name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip Client
        run: unzip nro-client-only.zip

      - name: Setup Unity
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 2021.3.16f1
          projectPath: . 
          allowDirtyBuild: true # Adicionei esta linha para corrigir o erro!

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DragonBoyBrasil
          path: build/Android/Android.apk
