name: Pegar Arquivo de Ativacao
on: [push]
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pedir Arquivo
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2021.3.16f1
      - name: Salvar Arquivo
        uses: actions/upload-artifact@v4
        with:
          name: arquivo-pedido
          path: ./*.alf
